api_version = "2026-01"

[[extensions]]
name = "B2B Delivery Rules"
handle = "b2b-delivery-rules"
uid = "019cd4c8-52c9-7d09-9afb-271a31ba13b7"
type = "function"
description = "Hides Free Shipping for B2C and paid shipping for B2B"

  [[extensions.targeting]]
  target = "cart.delivery-options.transform.run"
  input_query = "src/cart_delivery_options_transform_run.graphql"
  export = "cart-delivery-options-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
