api_version = "2026-01"

[[extensions]]
name = "B2B Delivery Rules"
handle = "b2b-delivery-rules"
uid = "f500c847-9b31-c041-83e9-dd7be2d62cd831f00ec1"
type = "function"
description = "Hides Free Shipping for B2C and paid shipping for B2B"

  [[extensions.targeting]]
  target = "cart.delivery-options.transform.run"
  input_query = "src/cart_delivery_options_transform_run.graphql"
  export = "cart-delivery-options-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
